// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM04TK1nZROLsUl0e4lBfs-oRiaya-9D0',
    appId: '1:398506341123:web:213496781c3c7cc8dfaf36',
    messagingSenderId: '398506341123',
    projectId: 'clube-do-desenho',
    authDomain: 'clube-do-desenho.firebaseapp.com',
    storageBucket: 'clube-do-desenho.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28A93MDZbXCylRcRdwiKm7EHwLUo_Fyg',
    appId: '1:398506341123:android:fc72ce8dd9a6dd7ddfaf36',
    messagingSenderId: '398506341123',
    projectId: 'clube-do-desenho',
    storageBucket: 'clube-do-desenho.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLWQXtEXxXJSsfHD_Na4t3qY_Et476ad4',
    appId: '1:398506341123:ios:4db40318ba8fd8ccdfaf36',
    messagingSenderId: '398506341123',
    projectId: 'clube-do-desenho',
    storageBucket: 'clube-do-desenho.appspot.com',
    iosClientId:
        '398506341123-b22fv0bn7slj2iqjvq6oke7di4i9k8tm.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
